google_billing_account_id_application = ""
google_folder_id_application          = ""
google_project_id_application         = ""
google_region_application             = "us-central1"
google_zone_application               = "us-central1-a"
